# Generated by Django 4.1.5 on 2023-06-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("form_App", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Common",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=50)),
                ("DateOfBirth", models.DateField(default="2022-11-21")),
                ("DateOfJoining", models.DateField(default="2022-11-21")),
                ("Address", models.CharField(max_length=100)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form_App.master",
                    ),
                ),
            ],
            options={"db_table": "common",},
        ),
    ]
