# Generated by Django 4.1.5 on 2023-06-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_App", "0002_common"),
    ]

    operations = [
        migrations.AlterModelTable(name="common", table="Common",),
    ]
